import { CubeGameV2, FACES, N, makeConfig, squareKey } from './engine-v2.mjs';
import { chooseCpuMove } from './cpu-v2.mjs';

const THREE=globalThis.THREE;if(!THREE)throw new Error('Three.js failed to load.');
const GLYPH={pawn:'♟',knight:'♞',bishop:'♝',rook:'♜',queen:'♛',king:'♚'},FACE_NAME={F:'FRONT',B:'BACK',L:'LEFT',R:'RIGHT',U:'CEILING',D:'FLOOR'};
let format='coalition',size=1,game=new CubeGameV2(makeConfig(format,size)),selected=null,selectedMoves=[],cpuPaused=false,cpuThinking=false,cpuTimer=null,toastTimer=null;
const dom={scene:document.querySelector('#scene'),modeLabel:document.querySelector('#modeLabel'),turnHero:document.querySelector('#turnHero'),modeTagline:document.querySelector('#modeTagline'),armyList:document.querySelector('#armyList'),history:document.querySelector('#history'),moveCount:document.querySelector('#moveCount'),setup:document.querySelector('#setupPanel'),settings:document.querySelector('#settingsBtn'),close:document.querySelector('#closeSetup'),tabs:document.querySelector('#formatTabs'),size:document.querySelector('#modeSize'),sizeLabel:document.querySelector('#sizeLabel'),setupName:document.querySelector('#setupModeName'),setupTagline:document.querySelector('#setupTagline'),seatList:document.querySelector('#seatList'),newGame:document.querySelector('#newGame'),humanSide:document.querySelector('#humanSide'),allCpu:document.querySelector('#allCpu'),difficulty:document.querySelector('#difficulty'),pace:document.querySelector('#cpuPace'),playPause:document.querySelector('#playPause'),stepCpu:document.querySelector('#stepCpu'),toast:document.querySelector('#toast'),selectionInfo:document.querySelector('#selectionInfo'),vrBtn:document.querySelector('#vrBtn')};

const scene=new THREE.Scene();scene.background=new THREE.Color(0x07080d);scene.fog=new THREE.FogExp2(0x07080d,.035);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.01,30);camera.position.set(0,0,.0001);camera.rotation.order='YXZ';
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.outputEncoding=THREE.sRGBEncoding;renderer.xr.enabled=true;dom.scene.appendChild(renderer.domElement);
scene.add(new THREE.AmbientLight(0xffffff,.58));const coreLight=new THREE.PointLight(0xd3ceff,1.25,8);scene.add(coreLight);
for(const[color,pos,intensity]of[[0xff315d,[-1.4,.8,.7],.36],[0x427dff,[1.4,-.7,-.9],.38],[0xffc74a,[.2,1.2,-1],.22]]){const light=new THREE.PointLight(color,intensity,5);light.position.set(...pos);scene.add(light)}
{const count=900,p=new Float32Array(count*3);for(let i=0;i<count;i++){const t=Math.random()*Math.PI*2,f=Math.acos(2*Math.random()-1),r=8+Math.random()*7;p[i*3]=r*Math.sin(f)*Math.cos(t);p[i*3+1]=r*Math.sin(f)*Math.sin(t);p[i*3+2]=r*Math.cos(f)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.BufferAttribute(p,3));scene.add(new THREE.Points(g,new THREE.PointsMaterial({color:0x8583aa,size:.025,transparent:true,opacity:.72})))}
function basisQuaternion(right,up,normal){return new THREE.Quaternion().setFromRotationMatrix(new THREE.Matrix4().makeBasis(new THREE.Vector3(...right),new THREE.Vector3(...up),new THREE.Vector3(...normal)))}
const colToU=c=>-1+(c+.5)*(2/N),rowToV=r=>1-(r+.5)*(2/N);
function textSprite(text,color,size=.1){const c=document.createElement('canvas');c.width=512;c.height=128;const x=c.getContext('2d');x.font='700 31px Segoe UI, sans-serif';x.fillStyle=color;x.textAlign='left';x.textBaseline='middle';x.fillText(text,8,64);const t=new THREE.CanvasTexture(c);t.minFilter=THREE.LinearFilter;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthTest:false}));s.scale.set(size*4,size,1);return s}
const faceGroups={},squareMeshes={},markers=[];let pieceObjects={};
function buildCube(){const cell=2/N;for(const[faceKey,face]of Object.entries(FACES)){const group=new THREE.Group();group.position.set(...face.normal);group.quaternion.copy(basisQuaternion(face.right,face.up,face.normal));scene.add(group);faceGroups[faceKey]=group;const backing=new THREE.Mesh(new THREE.PlaneGeometry(2.04,2.04),new THREE.MeshStandardMaterial({color:0x11131b,roughness:.88,metalness:.12,side:THREE.DoubleSide}));backing.position.z=.014;group.add(backing);for(let row=0;row<N;row++)for(let col=0;col<N;col++){const light=(row+col)%2===0,base=light?0xc2c3bd:0x292d35,mesh=new THREE.Mesh(new THREE.PlaneGeometry(cell*.955,cell*.955),new THREE.MeshStandardMaterial({color:base,roughness:.79,metalness:.05,side:THREE.DoubleSide,emissive:0x000000}));mesh.position.set(colToU(col),rowToV(row),0);mesh.userData={face:faceKey,row,col,base};group.add(mesh);squareMeshes[squareKey(faceKey,row,col)]=mesh}const label=textSprite(`${FACE_NAME[faceKey]} · ${faceKey}`,'#777b90',.1);label.position.set(-.94,.94,-.018);group.add(label);const fm=new THREE.MeshBasicMaterial({color:0x655e86,transparent:true,opacity:.44});for(const[x,y,w,h]of[[0,1.015,2.08,.018],[0,-1.015,2.08,.018],[-1.015,0,.018,2.08],[1.015,0,.018,2.08]]){const bar=new THREE.Mesh(new THREE.PlaneGeometry(w,h),fm);bar.position.set(x,y,-.006);group.add(bar)}}}
buildCube();
function pieceSprite(piece){const army=game.army(piece.armyId),c=document.createElement('canvas');c.width=160;c.height=160;const x=c.getContext('2d'),accent=army.color;x.beginPath();x.arc(80,80,64,0,Math.PI*2);x.fillStyle='rgba(5,6,10,.76)';x.fill();x.strokeStyle=accent;x.lineWidth=7;x.stroke();x.font='106px Georgia,serif';x.textAlign='center';x.textBaseline='middle';x.lineWidth=8;x.strokeStyle='rgba(0,0,0,.85)';x.fillStyle=accent;x.strokeText(GLYPH[piece.type],80,85);x.fillText(GLYPH[piece.type],80,85);const t=new THREE.CanvasTexture(c);t.minFilter=THREE.LinearFilter;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true}));s.scale.set(.225,.225,1);s.userData.pieceId=piece.id;s.userData.renderType=piece.type;s.userData.armyId=piece.armyId;return s}
function addStateRing(object,piece){if(!object.userData.magneticPiece)return;const color=piece.cubeEnabled?0x55e2ff:piece.breachReady?0xffc54c:null;if(color===null)return;const ring=new THREE.Mesh(new THREE.RingGeometry(.1,.12,32),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.78,depthTest:false,side:THREE.DoubleSide}));ring.position.z=.031;ring.renderOrder=6;ring.userData.stateRing=true;object.add(ring)}
function syncPieces(reset=false){if(reset){for(const o of Object.values(pieceObjects))o.parent?.remove(o);pieceObjects={}}const live=new Set(Object.values(game.board).map(p=>p.id));for(const[id,o]of Object.entries(pieceObjects))if(!live.has(+id)){o.parent?.remove(o);delete pieceObjects[id]}for(const[key,piece]of Object.entries(game.board)){const[face,row,col]=key.split(',');let object=pieceObjects[piece.id];if(!object||object.userData.renderType!==piece.type||object.userData.armyId!==piece.armyId){object?.parent?.remove(object);object=pieceSprite(piece);pieceObjects[piece.id]=object}else for(const child of[...object.children])if(child.userData.stateRing)object.remove(child);object.position.set(colToU(+col),rowToV(+row),-.034);faceGroups[face].add(object);addStateRing(object,piece)}}
function clearHighlights(){for(const mesh of Object.values(squareMeshes)){mesh.material.color.setHex(mesh.userData.base);mesh.material.emissive.setHex(0)}for(const m of markers)m.parent?.remove(m);markers.length=0;const last=game.history.at(-1);if(last)for(const sq of[last.from,last.to]){const mesh=squareMeshes[squareKey(sq.face,sq.row,sq.col)];if(mesh){mesh.material.color.setHex(0x5b526e);mesh.material.emissive.setHex(0x161020)}}}
function showMoves(from,moves,piece){clearHighlights();const chosen=squareMeshes[squareKey(from.face,from.row,from.col)];chosen.material.color.setHex(0x6b61e8);chosen.material.emissive.setHex(0x201b5a);const army=game.army(piece.armyId),cell=2/N;for(const move of moves){let geometry,color;if(move.climb){geometry=new THREE.RingGeometry(cell*.14,cell*.42,30);color=0xbe72ff}else if(!piece.cubeEnabled&&move.face===piece.homeFace&&move.row===army.gatewayRow){geometry=new THREE.RingGeometry(cell*.18,cell*.38,30);color=0xffc54c}else if(move.cornerChoice){geometry=new THREE.RingGeometry(cell*.17,cell*.35,28);color=0xc67cff}else if(move.capture){geometry=new THREE.RingGeometry(cell*.25,cell*.4,28);color=0xff4d62}else{geometry=new THREE.CircleGeometry(cell*.15,24);color=0x45d978}const marker=new THREE.Mesh(geometry,new THREE.MeshBasicMaterial({color,transparent:true,opacity:.92,depthTest:false,side:THREE.DoubleSide}));marker.position.set(colToU(move.col),rowToV(move.row),-.026);faceGroups[move.face].add(marker);markers.push(marker)}}
function updateSelectionInfo(piece){if(!selected||!piece){dom.selectionInfo.innerHTML='<strong>Select an army piece</strong><span>Gold = gateway ready · Violet = climb · Cyan = cube-enabled</span>';return}const a=game.army(piece.armyId),captures=selectedMoves.filter(m=>m.capture).length;dom.selectionInfo.innerHTML=`<strong>${a.commander} · ${a.face}${a.side} ${piece.type}</strong><span>${selectedMoves.length} legal moves · ${captures} captures · ${piece.cubeEnabled?'Cube-enabled':piece.breachReady?'Gateway ready':'Plane-bound'}</span>`}
function setSelection(face,row,col,piece){selected={face,row,col};selectedMoves=game.legalMovesAt(face,row,col);showMoves(selected,selectedMoves,piece);updateSelectionInfo(piece)}
function selectSquare(face,row,col){if(game.gameOver||game.currentArmy().controller==='cpu')return;const clicked=game.board[squareKey(face,row,col)],current=game.currentArmy();if(selected){const target=selectedMoves.find(m=>m.face===face&&m.row===row&&m.col===col);if(target){const piece=game.board[squareKey(selected.face,selected.row,selected.col)];playMove({from:selected,to:target,piece:piece.type});return}if(clicked?.armyId===current.id){setSelection(face,row,col,clicked);return}selected=null;selectedMoves=[];clearHighlights();updateSelectionInfo();return}if(clicked?.armyId===current.id)setSelection(face,row,col,clicked)}
function showToast(text){dom.toast.textContent=text;dom.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>dom.toast.classList.remove('show'),2800)}
function playMove(move){clearTimeout(cpuTimer);selected=null;selectedMoves=[];const result=game.play(move);syncPieces();clearHighlights();updateHUD();if(result?.piece?.breachReady)showToast('Gateway ready — this piece may climb next turn.');if(move.to.climb)showToast('Breakthrough! This piece is now cube-enabled.');if(['check','game-over','elimination'].includes(result?.state?.type))showToast(result.state.message);scheduleCpu()}
function updateHUD(){const a=game.currentArmy(),state=game.gameOver?(game.winner?`${game.winner} wins`:'Draw'):(a.controller==='cpu'?(cpuThinking?'CPU calculating':'CPU army'):'Human command');dom.modeLabel.textContent=game.config.label.toUpperCase();dom.modeTagline.textContent=game.config.tagline;dom.turnHero.innerHTML=`<div class="turn-orb" style="background:${a.color};color:${a.color}"></div><div class="turn-copy"><strong>${a.commander}</strong><span>${a.face}${a.side} · ${a.team} · ${state}</span></div>`;dom.armyList.innerHTML=game.armies.map((army,i)=>`<div class="army-row ${i===game.turnIndex&&!game.gameOver?'active':''} ${game.eliminated.has(army.id)?'eliminated':''}"><i class="player-swatch" style="background:${army.color}"></i><span class="face-code">${army.face}${army.side}</span><span class="commander">${army.commander}<small class="team"> · ${army.team}</small></span><span class="seat-type">${army.controller}</span></div>`).join('');dom.moveCount.textContent=`${game.history.length} move${game.history.length===1?'':'s'}`;dom.history.innerHTML=game.history.length?game.history.slice(-20).reverse().map((m,i)=>`<li data-index="${game.history.length-i}">${game.formatMove(m)}</li>`).join(''):'<li class="empty">The planes are ready.</li>';updateSelectionInfo(selected?game.board[squareKey(selected.face,selected.row,selected.col)]:null)}
function scheduleCpu(force=false){clearTimeout(cpuTimer);if(game.gameOver||cpuThinking)return;const army=game.currentArmy();if(army.controller!=='cpu'||(cpuPaused&&!force))return;cpuTimer=setTimeout(()=>{cpuThinking=true;updateHUD();setTimeout(()=>{const move=chooseCpuMove(game,army.id,dom.difficulty.value);cpuThinking=false;if(move)playMove(move);else{game.resolveTurnStart();updateHUD();scheduleCpu()}},30)},force?40:+dom.pace.value)}
function sizeOptions(){const values=format==='coalition'?[1,2,3,4,5,6]:format==='teams'?[2,3,4,5,6]:[4,6,8,10,12];dom.size.innerHTML=values.map(v=>`<option value="${v}">${format==='coalition'?`1 vs ${v}`:format==='teams'?`${v} vs ${v}`:`${v} players`}</option>`).join('');size=values.includes(size)?size:values[0];dom.size.value=String(size);dom.sizeLabel.textContent=format==='coalition'?'Opponents':format==='teams'?'Armies per side':'Players'}
function renderSeats(){dom.seatList.innerHTML=game.armies.map(a=>`<div class="seat"><i class="player-swatch" style="background:${a.color}"></i><span class="army-code">${a.face}${a.side}</span><span class="seat-copy"><b>${a.commander}</b><small>${a.team} · ${FACE_NAME[a.face]}</small></span><button data-army="${a.id}">${a.controller==='cpu'?'CPU':'Human'}</button></div>`).join('');dom.seatList.querySelectorAll('[data-army]').forEach(b=>b.addEventListener('click',()=>{const a=game.army(b.dataset.army);a.controller=a.controller==='cpu'?'human':'cpu';b.textContent=a.controller==='cpu'?'CPU':'Human';updateHUD();scheduleCpu()}))}
function startGame(){const config=makeConfig(format,size);game=new CubeGameV2(config);selected=null;selectedMoves=[];cpuThinking=false;dom.setupName.textContent=config.label;dom.setupTagline.textContent=config.tagline;syncPieces(true);clearHighlights();renderSeats();updateHUD();showToast(`${config.label} ready`);scheduleCpu()}
dom.tabs.addEventListener('click',e=>{const b=e.target.closest('[data-format]');if(!b)return;format=b.dataset.format;dom.tabs.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));sizeOptions();startGame()});dom.size.addEventListener('change',()=>{size=+dom.size.value;startGame()});dom.newGame.addEventListener('click',startGame);
dom.humanSide.addEventListener('click',()=>{if(format==='coalition')game.armies.forEach(a=>a.controller=a.team==='Solo'?'human':'cpu');else if(format==='teams')game.armies.forEach(a=>a.controller=a.team==='Axis A'?'human':'cpu');else game.armies.forEach((a,i)=>a.controller=i===0?'human':'cpu');renderSeats();updateHUD();scheduleCpu()});dom.allCpu.addEventListener('click',()=>{game.armies.forEach(a=>a.controller='cpu');cpuPaused=false;dom.playPause.textContent='Pause CPUs';renderSeats();updateHUD();scheduleCpu()});dom.playPause.addEventListener('click',()=>{cpuPaused=!cpuPaused;dom.playPause.textContent=cpuPaused?'Resume CPUs':'Pause CPUs';if(!cpuPaused)scheduleCpu()});dom.stepCpu.addEventListener('click',()=>scheduleCpu(true));dom.pace.addEventListener('change',scheduleCpu);
function setSetup(open){dom.setup.classList.toggle('closed',!open);dom.settings.setAttribute('aria-expanded',String(open))}dom.settings.addEventListener('click',()=>setSetup(dom.setup.classList.contains('closed')));dom.close.addEventListener('click',()=>setSetup(false));
const raycaster=new THREE.Raycaster();function pick(x,y){raycaster.setFromCamera(new THREE.Vector2(x/innerWidth*2-1,-y/innerHeight*2+1),camera);return raycaster.intersectObjects(Object.values(squareMeshes),false)[0]?.object}let dragging=false,moved=false,lastX=0,lastY=0,yaw=.35,pitch=-.12;renderer.domElement.addEventListener('pointerdown',e=>{dragging=true;moved=false;lastX=e.clientX;lastY=e.clientY;renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;if(Math.abs(dx)+Math.abs(dy)>3)moved=true;yaw-=dx*.0035;pitch=Math.max(-1.42,Math.min(1.42,pitch-dy*.0035));lastX=e.clientX;lastY=e.clientY});renderer.domElement.addEventListener('pointerup',e=>{dragging=false;if(!moved){const hit=pick(e.clientX,e.clientY);if(hit)selectSquare(hit.userData.face,hit.userData.row,hit.userData.col)}});renderer.domElement.addEventListener('wheel',e=>{camera.fov=Math.max(48,Math.min(92,camera.fov+Math.sign(e.deltaY)*3));camera.updateProjectionMatrix()},{passive:true});
function controllerSelect(e){const c=e.target,o=new THREE.Vector3().setFromMatrixPosition(c.matrixWorld),d=new THREE.Vector3(0,0,-1).applyQuaternion(new THREE.Quaternion().setFromRotationMatrix(c.matrixWorld));raycaster.set(o,d.normalize());const hit=raycaster.intersectObjects(Object.values(squareMeshes),false)[0]?.object;if(hit)selectSquare(hit.userData.face,hit.userData.row,hit.userData.col)}for(let i=0;i<2;i++){const c=renderer.xr.getController(i);c.addEventListener('selectstart',controllerSelect);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3(0,0,-2.5)]),new THREE.LineBasicMaterial({color:0xb8b1ff,transparent:true,opacity:.6}));c.add(line);scene.add(c)}
dom.vrBtn.addEventListener('click',async()=>{if(!navigator.xr){showToast('WebXR is unavailable here. Use VR preview or a headset browser.');return}try{if(!await navigator.xr.isSessionSupported('immersive-vr')){showToast('No compatible headset runtime detected.');return}const session=await navigator.xr.requestSession('immersive-vr',{optionalFeatures:['local-floor','bounded-floor']});await renderer.xr.setSession(session);dom.vrBtn.textContent='VR active';session.addEventListener('end',()=>dom.vrBtn.textContent='Enter VR')}catch{showToast('VR session could not start.')}});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});renderer.setAnimationLoop(()=>{if(!renderer.xr.isPresenting){camera.rotation.y=yaw;camera.rotation.x=pitch}coreLight.intensity=1.1+.06*Math.sin(performance.now()*.002);renderer.render(scene,camera)});
sizeOptions();startGame();
