import './logo-intro.mjs';
import './palette-nav.mjs';
import './classic-mode.mjs';
import { CubeGameV2 } from './engine-v2.mjs';
import { installUniversalCastling } from './universal-castling.mjs';
installUniversalCastling(CubeGameV2);
import './cube-promotion.mjs';
import './magnetic-models.mjs';
import './vr-capability.mjs';
import './turn-cue.mjs';
import './spectator-mode.mjs';
import './spectator-tagline.mjs';
import './classic-controls.mjs';
import './controller-persistence.mjs';
import './draw-resign.mjs';
import './match-study.mjs';
import './palette-mode.mjs';
import './castling-ui.mjs';
import './orientation-guides.mjs';
import './api-browser.mjs';
await import('./app-v2.mjs');
await import('./release-stability.mjs');
